### ISSUE TITLE
not working in Rstudio preview Version 1.4.953

### ISSUE THREAD

**Issue by verajosemanuel** [daattali/addinslist#117]
Addin list loads ok but i'm unable to select any item to install.

**Comment by daattali** [comment]
Thanks for the report! Was itworking for you in the latest stable rstudio and only fails when you use the Preview version?

**Comment by verajosemanuel** [comment]
that's correct

**Comment by espinielli** [comment]
I have same issue on Mac with RStudio Version 1.4.997 (preview)

**Comment by daattali** [comment]
This should be working now, sorry for taking so long.

**Comment by daattali** [comment]
This was actually caused by https://github.com/rstudio/shiny/issues/3225 (because a few years ago I didn't understand how these functions work)

**Comment by espinielli** [comment]
re-installed from GitHub and can confirm that it works!
Super thank you!

**Comment by verajosemanuel** [comment]
Working great! Thanks!
