### ISSUE TITLE
insertPrintInf

### ISSUE THREAD

**Issue by jbeaulie** [daattali/addinslist#138]
I don't really know how to wrap this into a proper pull request, but binding the following function to shortcut keys would be awesome:

#' Insert print(n=Inf)
#'
#' Call this function as an addin to insert \code{ print(n=Inf)} at the cursor position.
#'
#' @export
insertPrintInd <- function() {
  rstudioapi::insertText(" print(n=Inf)")
}

**Comment by daattali** [comment]
You'd have to go through the steps to create this as a proper RStudio addin. This repository is only meant as a place to list existing addins, I don't provide help in creating them. You'll need to go through RStudio documentation.

**Comment by dcomtois** [comment]
Are you aware you can use the option
`options(tibble.print_min = Inf)` ?

**Comment by jbeaulie** [comment]
I am aware, but prefer to invoke `print(n=Inf)` only when needed, as opposed to setting a global option. It is easy enough to write `%>% print(n=Inf)` when needed but I thought this might be a neat application for an add-in.

**Comment by dcomtois** [comment]
I see. I get the impression AddIn would be an overkill here. If you're using RStudio, have you looking into snippets?
