### ISSUE TITLE
Automated detection of Rstudio Addins on CRAN

### ISSUE THREAD

**Issue by haozhu233** [daattali/addinslist#19]
Hi, @daattali 

I like your approach of listing out all the RStudio addins. To enhance it, I wrote some script last week to automate the detection of RStudio Addins on CRAN, and put them into a shinyapp. I hope it can help. :D

Here is the link: https://haozhu233.shinyapps.io/rstudio_addins_on_cran/
Here is the source: https://github.com/haozhu233/rstudio_addins_on_cran

Also, I just submitted a PR with Yihui's testit and bookdown, discovered by this app. :)

**Comment by daattali** [comment]
Cool! I'm not sure how it can benefit this package right now , but it does look really nice. Maybe in the future when CRAN will have a lot more addins it will be more useful!

**Comment by daattali** [comment]
thanks!
