### ISSUE TITLE
addin drop down list not updated before restart R session

### ISSUE THREAD

**Issue by dracodoc** [daattali/addinslist#40]
I installed `addinlist` and installed some addins from the list. However the installed addin didn't appear in addin drop down menu. 

I have to restart R session or restart RStudio to see the newly installed addins.

Install addin manually through regular `install.packages` don't have this problem.

**Comment by daattali** [comment]
That has nothing to do with the addinlist - in fact, if you look at the source code (or the console when clicking on an addin), my package just calls `install.packages()` or `devtools::install_github()`.  I think when a package is installed using `install.packages()` then rstudio picks it up right away but when you install an addin from github then you have to restart

**Comment by dracodoc** [comment]
I tried again, it's like what you said. Interesting, when I tested my addin in a packrat project, the addin list got updated right after the installation...
