### ISSUE TITLE
Add https://github.com/r-lib/styler

### ISSUE THREAD

**Issue by luisspuerto** [daattali/addinslist#76]
Perhaps you can add that addin to the list. 

https://github.com/r-lib/styler

**Comment by daattali** [comment]
Thanks Luis, do you mind making a pull request?

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

Attend my 4-day workshop: Learn how to analyze data with R and create Shiny
apps. 15% discount to existing clients. Register here!
<https://www.eventbrite.com/e/modern-r-data-processing-visualization-and-reporting-with-r-tickets-39862492789?aff=deanemail>

**Comment by luisspuerto** [comment]
Not at all... do I just have to modify the table on the readme?

**Comment by daattali** [comment]
Yes, that's all it is :)

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

Attend my 4-day workshop: Learn how to analyze data with R and create Shiny
apps. 15% discount to existing clients. Register here!
<https://www.eventbrite.com/e/modern-r-data-processing-visualization-and-reporting-with-r-tickets-39862492789?aff=deanemail>

**Comment by luisspuerto** [comment]
done! https://github.com/daattali/addinslist/pull/77
